pipeline {
  agent any
  
  parameters {
    booleanParam(name: 'refresh', defaultValue: false, description: 'Read Jenkinsfile and exit.')
    choice(name: 'envType', choices: ['nonprod', 'prod'], description: 'Environment Type of Tenant.')
    string(name: 'tenantId', description: 'TenantId in Mission Control.')
  }

  environment {
    FUNCTION_NAME = 'friday-manageMCTenant'
  }

  stages {
    stage('Read Jenkinsfile') {
      when {
        expression { return params.refresh == true }
      }
      steps {
        echo("Refreshed Jenkins Job")
      }
    }
    stage('Run Jenkins Job') {
      when {
          expression { return params.refresh == false }
      }
      stages {
        stage('Verify Authorization') {
          steps {
            script {
              // Get Build User
              wrap([$class: 'BuildUser']) {
                env.CREATOR = "${BUILD_USER_ID}"
              }
              if(CREATOR == 'anonymous') {
                error('You have to login to run this job!!!')
              }
            }
          }
        }
        stage('Set Default Settings for a Tenant') {
          steps {
            script {
              def fileName = 'event.json'
              def event = [
                "env": "$envType",
                "action": "setDefaultSettings",
                "id": "$tenantId"
              ]
              writeJSON file: "$fileName", json: event
              sh "cat $fileName"
              sh "/usr/bin/python3 ./scripts/python/invoke_lambda.py --name=$FUNCTION_NAME --eventFile=$fileName"
            }
          }
        }
      }
    }
  }

  post {
    always {
      echo '==> Clean up built after run'
      cleanWs()
    }
    success {
      echo 'Job run success'
    }
    failure {
      echo 'Job run failed'
    }
  }
}