// Notify to channel
def notifyGChat(state, branch, version, commit, channel) {
  def DURATION = currentBuild.durationString.split(' and ')[0]
  hangoutsNotify message: "Status: *${currentBuild.result}*\nType: Frontend\nStage: CD - ${state} - EKS\nBranch: ${branch}\n*Version*: ${version}\nCommit: ${commit}\nDuration: ${DURATION}",
    token: "${channel}", threadByJob: true
}

def notifySlack(state, branch, version, commit, channel) {
  def DURATION = currentBuild.durationString.split(' and ')[0]
  def blocks = [
    [
      "type": "section",
      "text": [
        "type": "mrkdwn",
        "text": ":rocket: *Athena UI*"
      ]
    ],
      [
      "type": "divider"
    ],
    [
      "type": "section",
      "text": [
        "type": "mrkdwn",
        "text": "Status: *${currentBuild.result}*\nType: Frontend\nStage: CD - ${state} - EKS\nBranch: ${branch}\n*Version*: ${version}\nCommit: ${commit}\nDuration: ${DURATION}"
      ]
    ]
  ]
  slackSend(channel: "#${channel}", blocks: blocks)
}

// Function Configure Package for deployment to Tenant
def configurePackage(env, commit, env_type) {
  def configFileName = 'systemconfig'
  dir('dist/assets') {
    sh "cp ${configFileName}.json /tmp/${configFileName}.${env}.json"
    sh "update-fe-config ${configFileName} ${commit} ${env} ${env_type}"
    sh "cp /tmp/${configFileName}.${env}.json ${configFileName}.json"
    sh "cat ${configFileName}.json"
  }
}

// Function deploy Frontend to Tenant
def deployToTenant(env_type, domain, cloudfrontId) {
  echo "=> Deploy to ${domain}"
  AWS_CMD = 'aws'
  if(env_type == 'prod') {
    AWS_CMD = 'aws --profile prod'
  }
  dir('dist') {
    echo "=> Remove files on s3://${domain}"
    sh "${AWS_CMD} s3 rm s3://${domain} --recursive"
    echo "=> Upload files to s3://${domain}"
    sh "${AWS_CMD} s3 cp --acl public-read --recursive . s3://${domain}/"
    echo "=> Set Cache-Control for Service Worker"
    sh "${AWS_CMD} s3 cp --acl public-read --cache-control max-age=0 ./index.html s3://${domain}/"
    sh "${AWS_CMD} s3 cp --acl public-read --cache-control max-age=0 ./ngsw-worker.js s3://${domain}/"
    echo "=> Invalidate Cloudfront ${cloudfrontId}"
    sh "${AWS_CMD} cloudfront create-invalidation --distribution-id ${cloudfrontId} --paths \"/*\""
  }
}

pipeline {
  agent any

  parameters {
    booleanParam(name: 'refresh', defaultValue: false, description: 'Read Jenkinsfile and exit.')
    string(name: 'branch_name', description: 'Branch Name of the build which need to be deployed.')
    string(name: 'artifact_path', description: 'S3 Full Path of the Artifact to deploy.')
    string(name: 'build_version', description: 'Build Version which is used to tag release.')
    string(name: 'short_version', description: 'Version to add into UI.')
  }

  environment {
    ENV_TYPE = 'nonprod'
    GCHAT_TOKEN = "${GCHAT_TOKEN_ATH_CICD_FE}"
    GCHAT_TOKEN_BUILDVERSION = "${GCHAT_TOKEN_ATH_BUILDVERSION}"
    SLACK_CHANNEL = "${SLACK_ATH_CICD_FE}"
    SLACK_CHANNEL_BUILDVERSION = "${SLACK_ATH_BUILDVERSION}"
  }

  stages {
    stage('Read Jenkinsfile') {
      when {
        expression { return params.refresh == true }
      }
      steps {
        echo("Refreshed Jenkins Job")
      }
    }
    stage('Run Jenkins Job') {
      when {
          expression { return params.refresh == false }
      }
      stages {
        stage('Get environment information') {
          steps {
            echo "=> branch_name: ${params.branch_name}"
            script {
              env.ENV_NAME = ''
              env.ENV_NAME_2 = ''
              env.SHOULD_RUN_CD = 'yes'
              switch(branch_name) {
                case 'development-ktvn':
                  env.ENV_NAME = 'development-ktvn-eks'
                  env.DOMAIN = "development-ktvn-eks.athena-nonprod.com"
                  env.CF_ID = 'E2ZST9WNG5UC4O'
                  // env.ENV_NAME_2 = 'devleg'
                  // env.DOMAIN_2 = "athena-devleg.athena-nonprod.com"
                  // env.CF_ID_2 = 'E1KUDD96QI58BW'
                  break
                case 'ktvn':
                  env.ENV_NAME = 'ktvn-eks'
                  env.DOMAIN = "ktvn-eks.athena-nonprod.com"
                  env.CF_ID = 'E3JDIOUN8DWNCS'
                  break
                case 'development-fr':
                  env.ENV_NAME = 'development-fr-eks'
                  env.DOMAIN = "development-fr-eks.athena-nonprod.com"
                  env.CF_ID = 'E2U2ROE894YSFP'
                  break
                case 'fr':
                  env.ENV_NAME = 'fr-eks'
                  env.DOMAIN = "fr-eks.athena-nonprod.com"
                  env.CF_ID = 'E2AQ0HFX5CWHS8'
                  break
                // case 'develop':
                //   env.ENV_NAME = 'develop'
                //   env.DOMAIN = "develop.athena-nonprod.com"
                //   env.CF_ID = 'E20D1Z5BQWMZ9H'
                //   break
                // case 'master':
                //   env.ENV_NAME = 'master'
                //   env.DOMAIN = "master.athena-nonprod.com"
                //   env.CF_ID = ''
                //   break
                // case 'main':
                //   env.ENV_NAME = 'master'
                //   env.DOMAIN = "master.athena-nonprod.com"
                //   env.CF_ID = ''
                //   break
                default:
                  env.SHOULD_RUN_CD = 'no'
                  break
              }

              // check if branch_name match pattern "release/*" then set branch_name
              // def releasePattern = ~/release\/.+/
              // def matchRelease = releasePattern.matcher(branch_name).matches()
              // if(matchRelease) {
              //   env.ENV_NAME = 'release'
              //   env.DOMAIN = 'release.athena-nonprod.com'
              //   env.CF_ID = 'E37KC7S3NROET7'
              //   env.ENV_NAME_2 = 'release-2'
              //   env.DOMAIN_2 = "release-2.athena-nonprod.com"
              //   env.CF_ID_2 = 'E2SIZQ7QT5S3MA'
              //   env.SHOULD_RUN_CD = 'yes'
              // }

              // check if branch_name match pattern "hotfix/*" and env is ready to deploy
              def hotfixPattern = ~/hotfix\/.+/
              def matchHotfix = hotfixPattern.matcher(branch_name).matches()
              if(matchHotfix) {
                env.ENV_NAME = 'hotfix'
                // check hotfix env is available
                def hotfixInfa = sh('kubectl get ns | grep -w "^hotfix" ')
                if (hotfixInfa) {
                  env.SHOULD_RUN_CD = 'yes'
                }
                else {
                  env.SHOULD_RUN_CD = 'no'
                }
              }
            }
            echo "=> site: ${ENV_NAME}"
            echo "=> artifact_path: ${params.artifact_path}"
            echo "=> build_version: ${params.build_version}"
            echo "=> version: ${params.short_version}"
          }
        }
        stage('Pull Artifact') {
          when {
            equals expected: 'yes', actual: SHOULD_RUN_CD
          }
          steps {
            echo "=> Pull Artifact from S3"
            sh 'aws s3 cp ${artifact_path} .'
            sh 'tar zxvf *.tar.gz'
          }
        }
        stage('Deploy to environment') {
          when {
            equals expected: 'yes', actual: SHOULD_RUN_CD
          }
          steps {
            echo "=> Configure Environment"
            configurePackage("${ENV_NAME}", "${branch_name}-${short_version}", "${ENV_TYPE}")

            echo "=> Deploy ${DOMAIN} with CF_ID: ${CF_ID}"
            deployToTenant("${ENV_TYPE}", "${DOMAIN}", "${CF_ID}")
          }
          post {
            success {
              notifyGChat("Deploy to ${ENV_NAME}", "${branch_name}", "", "${short_version}", "${GCHAT_TOKEN}")
              notifySlack("Deploy to ${ENV_NAME}", "${branch_name}", "", "${short_version}", "${SLACK_CHANNEL}")
              script {
                if(ENV_NAME == 'release') {
                  echo "=> Notify Build Version"
                  notifyGChat("Create BUILD_VERSION", "${branch_name}", "${build_version}", "${short_version}", "${GCHAT_TOKEN_BUILDVERSION}")
                  notifySlack("Create BUILD_VERSION", "${branch_name}", "${build_version}", "${short_version}", "${SLACK_CHANNEL_BUILDVERSION}")
                }
              }
            }
            failure {
              notifyGChat("${ENV_NAME}", "${branch_name}", "", "${short_version}", "${GCHAT_TOKEN}")
              notifySlack("${ENV_NAME}", "${branch_name}", "", "${short_version}", "${SLACK_CHANNEL}")
              script {
                if(ENV_NAME == 'release') {
                  echo "=> Notify Build Version"
                  notifyGChat("Create BUILD_VERSION", "${branch_name}", "${build_version}", "${short_version}", "${GCHAT_TOKEN_BUILDVERSION}")
                  notifySlack("Create BUILD_VERSION", "${branch_name}", "${build_version}", "${short_version}", "${SLACK_CHANNEL_BUILDVERSION}")
                }
              }
            }
          }
        }
        // stage('Deploy to environment ${ENV_NAME_2}') {
        //   when {
        //     equals expected: 'yes', actual: SHOULD_RUN_CD
        //     not {  equals expected: '', actual: ENV_NAME_2 }
        //   }
        //   steps {
        //     echo "=> Configure Environment"
        //     configurePackage("${ENV_NAME_2}", "${branch_name}-${short_version}", "${ENV_TYPE}")

        //     echo "=> Deploy ${DOMAIN_2} with CF_ID: ${CF_ID}"
        //     deployToTenant("${ENV_TYPE}", "${DOMAIN_2}", "${CF_ID_2}")
        //   }
        //   post {
        //     success {
        //       notifyGChat("Deploy to ${ENV_NAME_2}", "${branch_name}", "", "${short_version}", "${GCHAT_TOKEN}")
        //       notifySlack("Deploy to ${ENV_NAME_2}", "${branch_name}", "", "${short_version}", "${SLACK_CHANNEL}")
        //     }
        //     failure {
        //       notifyGChat("${ENV_NAME_2}", "${branch_name}", "", "${short_version}", "${GCHAT_TOKEN}")
        //       notifySlack("${ENV_NAME_2}", "${branch_name}", "", "${short_version}", "${SLACK_CHANNEL}")
        //     }
        //   }
        // }
      }
    }
  }

  post {
    always {
      cleanWs()
    }
    success {
      echo "=> Deploy Success"
    }
    failure {
      echo "=> Deploy Failure"
    }
  }
}